version: '3.8'
 
services:
  # 1. Aplicação Principal (Frontend Flet)
  opera-app:
    # build: .
    image: proj_app--llm-api-docs_analyzer_3-opera-app
    container_name: opera-ia-frontend
    restart: unless-stopped
    ports:
      - "8550:8550"
      - "80:8550"    # Adiciona a porta 80 escutando e jogando para a 8550
      - "8080:8550"  # terceira porta opcional    
    volumes:
      - opera_data:/app/data
      # Mapeamento de código (Hot-reload no servidor)
      - ./SOURCE:/app/SOURCE
      - ./assets:/app/assets
      - ./logs:/app/logs      
      - ./uploads_temp:/app/uploads_temp      
      - ./run_server.py:/app/run_server.py
    environment:
      - APP_MODE=server
      - PORT=8550
      - FLET_SECRET_KEY=oTSHabCz0q5slF4OjKHUmh1zr/fVZDvtoZMECrwYJRI=
      - TZ=America/Sao_Paulo
      - ML_ENGINE_URL=http://ml-engine:8001
      - SERVER_DATA_DIR=/app/data
      - DPF_SECRET_SIST_OPERA_FIREBASE_ENCRYPTION_KEY=m0MMyi6H8ih9wjRTDZPsV6lqJKUQiI8KuuThQjK9eHc=      
      # --- Configuração de Proxy Corporativo ---
      # Descomente e preencha com os dados da rede (ex: http://usuario:senha@10.x.x.x:porta)
      - HTTP_PROXY=http://proxy.dpf.gov.br:8080
      - HTTPS_PROXY=http://proxy.dpf.gov.br:8080
      # Impede que o tráfego interno (motor de ML) seja enviado para o proxy corporativo:
      - NO_PROXY=localhost,127.0.0.1,10.2.2.10,10.2.2.10:31893,ml-engine
    depends_on:
      - ml-engine

  # 2. Painel Administrativo (Streamlit)
  opera-admin:
    # build: . # Usa exatamente a mesma imagem do opera-app
    image: proj_app--llm-api-docs_analyzer_3-opera-app
    container_name: opera-ia-admin
    restart: unless-stopped
    # Sobrescreve o CMD do Dockerfile para rodar o Streamlit
    command: ["streamlit", "run", "run_admin_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - opera_data:/app/data
      # Mapeamento de código
      - ./SOURCE:/app/SOURCE
      - ./admin_py:/app/admin_py
      - ./run_admin_streamlit.py:/app/run_admin_streamlit.py
    environment:
      - SERVER_DATA_DIR=/app/data
      - DPF_SECRET_SIST_OPERA_FIREBASE_ENCRYPTION_KEY=m0MMyi6H8ih9wjRTDZPsV6lqJKUQiI8KuuThQjK9eHc=
      - TZ=America/Sao_Paulo
    depends_on:
      - ml-engine

  # 3. Motor de Machine Learning (FastAPI)
  ml-engine:
    # build: 
    #  context: ../Proj_App   -- LLM-API - Vector_Engine_2
    image: proj_app--llm-api-docs_analyzer_3-ml-engine
    container_name: opera-ia-ml-engine
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
    # O engine de ML muda pouco, mas se quiser mapear o código dele também:
    # volumes:
    #   - ../Proj_App   -- LLM-API - Vector_Engine_2/engine.py:/app/engine.py

volumes:
  opera_data:
    name: opera_persistent_data